---
  AWSTemplateFormatVersion: 2010-09-09

  Description: The bosh-lite server.

  Parameters:
    AWSMusingsS3URL:
      Type: String
      Description: S3 path to aws-musings.
    BOSHLiteCFAdminPassword:
      Type: String
      Description: The password for the admin account to Cloud Foundry.
    BOSHLiteELBSecurityGroupId:
      Type: AWS::EC2::SecurityGroup::Id
      Description: The id of the bosh-lite ELB security group.
    BOSHLiteELBSSLCertificateId:
      Type: String
      Description: TODO: Not currently used. The ARN id of the SSL/TLS certificate used by the ELB to communicate with
        clients.
    BOSHLiteImageId:
      Type: AWS::EC2::Image::Id
      Description: The image id of the bosh-lite instance.
    BOSHLiteInstanceName:
      Type: String
      Default: bosh-lite1
      Description: The DNS name of the bosh-lite instance.
      AllowedPattern: "[a-z0-9\\-]*"
      ConstraintDescription: must contain only lowercase letters, numbers and dashes
    BOSHLiteInstanceSecurityGroupId:
      Type: AWS::EC2::SecurityGroup::Id
      Description: The id of the bosh-lite instance security group.
    BOSHLiteInstanceType:
      Type: String
      Description: The instance type of the bosh-lite instance.
    BOSHLitePublicSubnetId:
      Type: AWS::EC2::Subnet::Id
      Description: The id of the bosh-lite public subnet.
    BOSHLitePrivateSubnetId:
      Type: AWS::EC2::Subnet::Id
      Description: The id of the bosh-lite private subnet.
    BOSHLiteSpotPrice:
      Type: String
      Description: The spot price in US dollars of the bosh-lite instance.
      AllowedPattern: "[0-9]*[\\.]?[0-9]*"
      ConstraintDescription: must be empty or contain a decimal number
    DNSZone:
      Type: String
      Description: The DNS zone name of the VPC (should not end in 'vpc', used in naming the instance).
      AllowedPattern: "[a-z0-9\\-]*"
      ConstraintDescription: must contain only lowercase letters, numbers and dashes
    FullyQualifiedExternalParentDNSZone:
      Type: String
      Description: The external parent DNS zone (should not start or end with .). Optional, Route 53 resources will be
        created if specified.
      AllowedPattern: "([a-z][a-z0-9\-.]*[a-z0-9])|(^$)"
      ConstraintDescription: must contain only lowercase letters, numbers, dashes and dots, optional
    FullyQualifiedInternalParentDNSZone:
      Type: String
      Description: The internal parent DNS zone (should not start or end with .).
      AllowedPattern: "[a-z][a-z0-9\\-.]*[a-z0-9]"
      ConstraintDescription: must contain only lowercase letters, numbers, dashes and dots
    InternalKeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: SSH key name used to connect with internal servers.
    VPCId:
      Type: AWS::EC2::VPC::Id
      Description: The id of the VPC in which the resources will be created.

  Resources:
    BOSHLiteLaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Metadata:
        "AWS::CloudFormation::Init":
          config:
            files:
              /etc/cfn/cfn-hup.conf:
                source: !Sub "${AWSMusingsS3URL}/common/cfn-hup.conf"
                context:
                  STACK_ID: !Ref "AWS::StackId"
                  REGION: !Ref "AWS::Region"
                mode: 000400
                owner: root
                group: root
              /etc/cfn/hooks.d/cfn-auto-reloader.conf:
                source: !Sub "${AWSMusingsS3URL}/common/cfn-auto-reloader.conf"
                context:
                  STACK_ID: !Ref "AWS::StackId"
                  REGION: !Ref "AWS::Region"
                  INSTANCE_NAME: BOSHLiteInstance
              /etc/dhcp/dhclient.conf:
                source: !Sub "${AWSMusingsS3URL}/common/dhclient.conf"
                context:
                  FQDN: !Sub "${BOSHLiteInstanceName}${DNSZone}.${FullyQualifiedInternalParentDNSZone}"
      Properties:
        AssociatePublicIpAddress: false
        BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
        - DeviceName: /dev/sdb
          VirtualName: ephemeral0
        ImageId: !Ref BOSHLiteImageId
        InstanceType: !Ref BOSHLiteInstanceType
        KeyName: !Ref InternalKeyName
        SecurityGroups: [ !Ref BOSHLiteInstanceSecurityGroupId ]
        SpotPrice: !Ref BOSHLiteSpotPrice
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash

              set -e -x

              export HOSTNAME=${BOSHLiteInstanceName}
              export STACK_NAME="${AWS::StackName}"
              export RESOURCE=BOSHLiteLaunchConfig
              export REGION="${AWS::Region}"
              export AWS_MUSINGS_S3_URL="${AWSMusingsS3URL}"

              export EXTRA_PACKAGES="bundler"
              export AUTO_SCALING_GROUP=BOSHLiteAutoScalingGroup

              curl --output /tmp/bootstrap.sh --silent $AWS_MUSINGS_S3_URL/common/bootstrap.sh
              source /tmp/bootstrap.sh
              aws-bootstrap

              export BOSH_LITE_URL="${DNSZone}.${FullyQualifiedExternalParentDNSZone}"
              export BOSH_LITE_CF_ADMIN_PASSWORD="${BOSHLiteCFAdminPassword}"

              curl --output /etc/init.d/bosh-lite-run-once --silent "$AWS_MUSINGS_S3_URL/bosh-lite/run-once.sh"
              chmod +x /etc/init.d/bosh-lite-run-once
              sed -i -e "s/STACK_NAME/$STACK_NAME/g" /etc/init.d/bosh-lite-run-once
              sed -i -e "s/RESOURCE/$AUTO_SCALING_GROUP/g" /etc/init.d/bosh-lite-run-once
              sed -i -e "s/REGION/$REGION/g" /etc/init.d/bosh-lite-run-once
              update-rc.d bosh-lite-run-once defaults 99

              curl --output /usr/local/bootstrap-bosh-lite.sh --silent "$AWS_MUSINGS_S3_URL/bosh-lite/bootstrap.sh"
              sed -i -e "s/BOSH_LITE_URL/$BOSH_LITE_URL/g" /usr/local/bootstrap-bosh-lite.sh
              sed -i -e "s/BOSH_LITE_CF_ADMIN_PASSWORD/$BOSH_LITE_CF_ADMIN_PASSWORD/g" \
                /usr/local/bootstrap-bosh-lite.sh
              chmod +x /usr/local/bootstrap-bosh-lite.sh

              # Success (aws-signal-success) is signalled from the run-once script
              reboot
    BOSHLiteAutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        LaunchConfigurationName: !Ref BOSHLiteLaunchConfig
        LoadBalancerNames: [ !Ref BOSHLiteLoadBalancer ]
        MaxSize: 1
        MinSize: 1
        Tags:
        - Key: Name
          Value: !Sub "${DNSZone}-${BOSHLiteInstanceName}-asg"
          PropagateAtLaunch: true
        VPCZoneIdentifier: [ !Ref BOSHLitePrivateSubnetId ]
      CreationPolicy:
        ResourceSignal:
          Timeout: PT1H
      DependsOn: [ BOSHLiteLaunchConfig, BOSHLiteLoadBalancer ]

    BOSHLiteLoadBalancer:
      Type: AWS::ElasticLoadBalancing::LoadBalancer
      Properties:
        LoadBalancerName: !Sub "${DNSZone}-${BOSHLiteInstanceName}-elb"
        Tags:
        - Key: Name
          Value: !Sub "${DNSZone}-${BOSHLiteInstanceName}-elb"
        HealthCheck:
          Target: TCP:443
          HealthyThreshold: 3
          UnhealthyThreshold: 5
          Interval: 30
          Timeout: 5
        Listeners:
        - LoadBalancerPort: 443
          Protocol: TCP
          InstancePort: 443
          InstanceProtocol: TCP
        SecurityGroups: [ !Ref BOSHLiteELBSecurityGroupId ]
        Subnets: [ !Ref BOSHLitePublicSubnetId ]

    BOSHLiteLoadBalancerRecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: !Sub "${FullyQualifiedExternalParentDNSZone}."
        Name: !Sub "*.${DNSZone}.${FullyQualifiedExternalParentDNSZone}"
        AliasTarget:
          DNSName: !GetAtt BOSHLiteLoadBalancer.CanonicalHostedZoneName
          HostedZoneId: !GetAtt BOSHLiteLoadBalancer.CanonicalHostedZoneNameID
        Type: A
      DependsOn: BOSHLiteLoadBalancer
