---
  AWSTemplateFormatVersion: 2010-09-09

  Description: elasticsearch networking

  Parameters:
    ElasticsearchAvailabilityZone:
      Type: AWS::EC2::AvailabilityZone::Name
      Default: us-east-1a
      Description: The availability zone where elasticsearch resources will be created.
    ElasticsearchPrivateThreeOctetCIDRBlock:
      Type: String
      Default: 10.0.58
      Description: The first 24 bits of the first CIDR block for the elasticsearch private subnet.
      AllowedPattern: "(\d{1,3})\.(\d{1,3})\.(\d{1,3})"
      ConstraintDescription: must be the first three digits of a valid IP CIDR of the form x.x.x
    NetworkACLId:
      Type: String
      Description: The id of the network access control list used to protect instances in this project.
    PrivateRouteTableId:
      Type: String
      Description: The id of the private route table associated with the project's private subnets.
    VPCId:
      Type: AWS::EC2::VPC::Id
      Description: The id of the VPC in which the resources will be created.

  Mappings:
    AZRegionMap:
      us-east-1: { a: us-east-1a, b: us-east-1b, c: us-east-1c }
      us-west-2: { a: us-west-2a, b: us-west-2b, c: us-west-2c }

  Resources:
    ElasticsearchPrivateSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: { "Fn::Join": [ ., [ { Ref: ElasticsearchPrivateThreeOctetCIDRBlock }, 0/24 ] ] }
        AvailabilityZone: { "Fn::FindInMap": [ AZRegionMap, { Ref: "AWS::Region" }, a] }
        VpcId: { Ref: VPCId }
        Tags:
        - Key: Name
          Value: { "Fn::Join": [ -, [ { Ref: "AWS::StackName" }, private-subnet ] ] }

    ElasticsearchPrivateSubnetRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: { Ref: PrivateRouteTableId }
        SubnetId: { Ref: ElasticsearchPrivateSubnet }

    ElasticsearchPrivateSubnetNetworkACLAssociation:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: { Ref: NetworkACLId }
        SubnetId: { Ref: ElasticsearchPrivateSubnet }

    ElasticsearchInstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: elasticsearch instance security group
        VpcId: { Ref: VPCId }
        Tags:
        - Key: Name
          Value: { "Fn::Join": [ -, [ { Ref: "AWS::StackName" }, instance-sg ] ] }
        SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 10.0.0.0/8
        SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  Outputs:
    ElasticsearchPrivateSubnetId:
      Description: The id of the elasticsearch private subnet.
      Value: { Ref: ElasticsearchPrivateSubnet }
    ElasticsearchInstanceSecurityGroupId:
      Description: The id of the elasticsearch instance security group.
      Value: { Ref: ElasticsearchInstanceSecurityGroup }
