---
  AWSTemplateFormatVersion: 2010-09-09

  Description: The elasticsearch server.

  Parameters:
    AWSMusingsS3URL:
      Type: String
      Description: S3 path to aws-musings.
    ElasticsearchImageId:
      Type: AWS::EC2::Image::Id
      Description: The image id of the elasticsearch instance.
    ElasticsearchInstanceName:
      Type: String
      Default: elasticsearch1
      Description: The DNS name of the elasticsearch instance.
      AllowedPattern: "[a-z0-9\\-]*"
      ConstraintDescription: must contain only lowercase letters, numbers and dashes
    ElasticsearchInstanceSecurityGroupId:
      Type: AWS::EC2::SecurityGroup::Id
      Description: The id of the elasticsearch instance security group.
    ElasticsearchInstanceType:
      Type: String
      Description: The instance type of the elasticsearch instance.
    ElasticsearchPrivateSubnetId:
      Type: AWS::EC2::Subnet::Id
      Description: The id of the elasticsearch private subnet.
    ElasticsearchSpotPrice:
      Type: String
      Description: The spot price in US dollars of the elasticsearch instance.
      AllowedPattern: "[0-9]*[\\.]?[0-9]*"
      ConstraintDescription: must be empty or contain a decimal number
    DNSZone:
      Type: String
      Description: The DNS zone name of the VPC (should not end in 'vpc', used in naming the instance).
      AllowedPattern: "[a-z0-9\\-]*"
      ConstraintDescription: must contain only lowercase letters, numbers and dashes
    FullyQualifiedInternalParentDNSZone:
      Type: String
      Description: The internal parent DNS zone (should not start or end with .).
      AllowedPattern: "[a-z][a-z0-9\\-.]*[a-z0-9]"
      ConstraintDescription: must contain only lowercase letters, numbers, dashes and dots
    InternalKeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: SSH key name used to connect with internal servers.
    VPCId:
      Type: AWS::EC2::VPC::Id
      Description: The id of the VPC in which the resources will be created.

  Resources:
    ElasticsearchLaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Metadata:
        "AWS::CloudFormation::Init":
          config:
            files:
              /etc/cfn/cfn-hup.conf:
                source: { "Fn::Join": [ /, [ { Ref: AWSMusingsS3URL }, common/cfn-hup.conf ] ] }
                context:
                  STACK_ID: { Ref: "AWS::StackId" }
                  REGION: { Ref: "AWS::Region" }
                mode: 000400
                owner: root
                group: root
              /etc/cfn/hooks.d/cfn-auto-reloader.conf:
                source: { "Fn::Join": [ /, [ { Ref: AWSMusingsS3URL }, common/cfn-auto-reloader.conf ] ] }
                context:
                  STACK_ID: { Ref: "AWS::StackId" }
                  REGION: { Ref: "AWS::Region" }
                  INSTANCE_NAME: ElasticsearchInstance
              /etc/dhcp/dhclient.conf:
                source: { "Fn::Join": [ /, [ { Ref: AWSMusingsS3URL }, common/dhclient.conf ] ] }
                context:
                  FQDN: { "Fn::Join": [ "", [ { Ref: ElasticsearchInstanceName },
                    { Ref: DNSZone }, ., { Ref: FullyQualifiedInternalParentDNSZone } ] ] }
      Properties:
        AssociatePublicIpAddress: false
        BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: 30
        - DeviceName: /dev/sdb
          VirtualName: ephemeral0
        ImageId: { Ref: ElasticsearchImageId }
        InstanceType: { Ref: ElasticsearchInstanceType }
        KeyName: { Ref: InternalKeyName }
        SecurityGroups: [ { Ref: ElasticsearchInstanceSecurityGroupId } ]
        SpotPrice: { Ref: ElasticsearchSpotPrice }
        UserData:
          "Fn::Base64":
            "Fn::Join": [ "", [
              "#!/bin/bash\n",

              "set -e -x\n",

              "export HOSTNAME=", { Ref: ElasticsearchInstanceName}, "\n",
              "export STACK_NAME=\"", { Ref: "AWS::StackName" }, "\"\n",
              "export RESOURCE=ElasticsearchLaunchConfig\n",
              "export REGION=\"", { Ref: "AWS::Region" }, "\"\n",
              "export AWS_MUSINGS_S3_URL=\"", { Ref: AWSMusingsS3URL }, "\"\n",

              "export EXTRA_PACKAGES=\"openjdk-7-jre\"\n",
              "export AUTO_SCALING_GROUP=ElasticsearchAutoScalingGroup\n",

              "curl --output /tmp/bootstrap.sh --silent $AWS_MUSINGS_S3_URL/common/bootstrap.sh\n",
              "source /tmp/bootstrap.sh\n",
              "aws-bootstrap\n",

              "curl --output /tmp/elastic.deb --silent https://download.elastic.co/elasticsearch/release/",
                "org/elasticsearch/distribution/deb/elasticsearch/2.3.2/elasticsearch-2.3.2.deb\n",
              "dpkg --install /tmp/elastic.deb\n",
              "update-rc.d elasticsearch defaults 95 10\n",
              "echo 'network.bind_host: \"0.0.0.0\"' >> /etc/elasticsearch/elasticsearch.yml\n",
              "echo 'network.publish_host: _non_loopback:ipv4_' >> /etc/elasticsearch/elasticsearch.yml\n",

              "# All done so signal success\n",
              "aws-signal-success\n",
              "reboot\n"
            ] ]
    ElasticsearchAutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        LaunchConfigurationName: { Ref: ElasticsearchLaunchConfig }
        MaxSize: 1
        MinSize: 1
        Tags:
        - Key: Name
          Value: { "Fn::Join": [ -, [ { Ref: DNSZone }, { Ref: ElasticsearchInstanceName }, asg ] ] }
          PropagateAtLaunch: true
        VPCZoneIdentifier: [ { Ref: ElasticsearchPrivateSubnetId } ]
      CreationPolicy:
        ResourceSignal:
          Timeout: PT10M
      DependsOn: [ ElasticsearchLaunchConfig ]
