---
  AWSTemplateFormatVersion: 2010-09-09

  Description: The VPC's DNS server.

  Parameters:
    AWSMusingsS3URL:
      Type: String
      Description: S3 path to aws-musings.
    DNSZone:
      Type: String
      Description: The DNS zone name of the VPC (should not end in 'vpc', .FullyQualifiedInternalParentDNSZone will be
        appended).
      AllowedPattern: "[a-z0-9\\-]*"
      ConstraintDescription: must contain only lowercase letters, numbers and dashes
    FullyQualifiedInternalParentDNSZone:
      Type: String
      Description: The internal parent DNS zone (should not start or end with .).
      AllowedPattern: "[a-z][a-z0-9\\-.]*[a-z0-9]"
      ConstraintDescription: must contain only lowercase letters, numbers, dashes and dots
    ImageId:
      Type: AWS::EC2::Image::Id
      Description: The AMI used to create the instance.
    KeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: SSH key name used to connect to the DNS server.
    SecondOctet:
      Type: Number
      MinValue: 0
      MaxValue: 255
      Description: The second octet of the CIDR block for the VPC.
    SecurityGroupId:
      Type: AWS::EC2::SecurityGroup::Id
      Description: The id of the security group protecting the DNS server.
    SubnetId:
      Type: AWS::EC2::Subnet::Id
      Description: The id of the subnet where the server will be added.

  Resources:
    DNSInstance:
      Type: AWS::EC2::Instance
      Metadata:
        "AWS::CloudFormation::Init":
          config:
            packages:
              yum: { bind: [] }
            services:
              sysvinit:
                named:
                  enabled: true
                  files: [ /etc/named.conf ]
            files:
              /etc/named.conf:
                source: !Sub "${AWSMusingsS3URL}/infrastructure/dns/named.conf"
                context:
                  DNS_ZONE: !Ref DNSZone
                  FULLY_QUALIFIED_PARENT_DNS_ZONE: !Ref FullyQualifiedInternalParentDNSZone
                  SECOND_OCTET: !Ref SecondOctet
              /var/named/dynamic/named.vpc:
                source: !Sub "${AWSMusingsS3URL}/infrastructure/dns/named.vpc"
                context:
                  DNS_ZONE: !Ref DNSZone
                  FULLY_QUALIFIED_PARENT_DNS_ZONE: !Ref FullyQualifiedInternalParentDNSZone
                  SECOND_OCTET: !Ref SecondOctet
                mode: 000644
                owner: named
                group: named
              /var/named/dynamic/named.vpc-rev:
                  source: !Sub "${AWSMusingsS3URL}/infrastructure/dns/named.vpc-rev"
                  context:
                    DNS_ZONE: !Ref DNSZone
                    FULLY_QUALIFIED_PARENT_DNS_ZONE: !Ref FullyQualifiedInternalParentDNSZone
                    SECOND_OCTET: !Ref SecondOctet
                  mode: 000644
                  owner: named
                  group: named
              /etc/sysconfig/network-scripts/ifcfg-eth0:
                source: !Sub "${AWSMusingsS3URL}/infrastructure/dns/ifcfg-eth0"
              /etc/resolv.conf:
                content:
                  !Sub |
                    search ${DNSZone}.${FullyQualifiedInternalParentDNSZone}
                      nameserver 127.0.0.1,10.${SecondOctet}.0.2

              /etc/cfn/cfn-hup.conf:
                source: !Sub "${AWSMusingsS3URL}/common/cfn-hup.conf"
                context:
                  STACK_ID: !Ref "AWS::StackId"
                  REGION: !Ref "AWS::Region"
                mode: 000400
                owner: root
                group: root
              /etc/cfn/hooks.d/cfn-auto-reloader.conf:
                source: !Sub "${AWSMusingsS3URL}/common/cfn-auto-reloader.conf"
                context:
                  STACK_ID: !Ref "AWS::StackId"
                  REGION: !Ref "AWS::Region"
                  INSTANCE_NAME: DNSInstance

              /etc/dhcp/dhclient.conf:
                source: !Sub "${AWSMusingsS3URL}/common/dhclient.conf"
                context:
                  FQDN: !Sub "${DNSZone}-dns.${DNSZone}.${FullyQualifiedInternalParentDNSZone}"

              /home/ec2-user/.bashrc:
                source: !Sub "${AWSMusingsS3URL}/common/bashrc.sh"
                mode: 000644
                owner: ec2-user
                group: ec2-user
              /root/.bashrc:
                source: !Sub "${AWSMusingsS3URL}/common/bashrc.sh"
                mode: 000644
                owner: root
                group: root
      Properties:
        DisableApiTermination: false
        ImageId: !Ref ImageId
        InstanceType: t2.micro
        KeyName: !Ref KeyName
        Monitoring: false
        Tags:
        - Key: Name
          Value: !Sub "${DNSZone}-dns"
        NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          PrivateIpAddresses:
          - PrivateIpAddress: !Sub "10.${SecondOctet}.2.10"
            Primary: true
          GroupSet: [ !Ref SecurityGroupId ]
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash

              set -e -x

              export HOSTNAME=dns
              export STACK_NAME="${AWS::StackName}"
              export RESOURCE=NATInstance
              export REGION="${AWS::Region}"
              export AWS_MUSINGS_S3_URL="${AWSMusingsS3URL}"

              curl --output /tmp/bootstrap.sh --silent $AWS_MUSINGS_S3_URL/common/bootstrap.sh
              source /tmp/bootstrap.sh
              aws-bootstrap

              mkdir /var/log/named
              chown named:named /var/log/named

              # All done so signal success
              aws-signal-success
              reboot
      CreationPolicy:
        ResourceSignal:
          Timeout: PT10M

  Outputs:
    PrivateIP:
      Value: !GetAtt DNSInstance.PrivateIp
