AWSTemplateFormatVersion: 2010-09-09

Description: |
  An external DNS hosted zone. Note this is a separate stack as the public zone it creates can be shared among
  several full infrastructure stacks.

Parameters:
  FullyQualifiedExternalParentDNSZone:
    Type: String
    Description: The external parent DNS zone (should not start or end with .).
    AllowedPattern: "[a-z][a-z0-9\\-.]*[a-z0-9]"
    ConstraintDescription: must contain only lowercase letters, numbers, dashes and dots
  StackEnv:
    Type: String
    Description: The environment name.
    AllowedPattern: "[a-z0-9\\-]*"
    ConstraintDescription: must contain only lowercase letters, numbers and dashes
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the VPC in which the resources will be created.

Resources:
  ExternalHostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Sub "${StackEnv}.${FullyQualifiedExternalParentDNSZone}"

Outputs:
  ExternalHostedZoneId:
    Description: The id of the external DNS hosted zone.
    Value: !Ref ExternalHostedZone
  ExternalHostedZoneNameServers:
    Description: The name servers to be used in creating a NS record to complete delegation to this zone.
    Value: !Join
    - " "
    - !GetAtt ExternalHostedZone.NameServers
  FullyQualifiedExternalDNSZone:
    Description: The fully qualified external DNS zone (not the parent zone passed in as a parameter).
    Value: !Sub "${StackEnv}.${FullyQualifiedExternalParentDNSZone}"
