AWSTemplateFormatVersion: 2010-09-09

Description: |
  An internal DNS hosted zone. Note this is a separate stack as the private zone it creates can be shared among
  several full infrastructure stacks.

Parameters:
  FullyQualifiedExternalDNSZone:
    Type: String
    Description: The external DNS zone (should not start or end with .).
  InternalDNSZone:
    Type: String
    Description: The internal DNS zone (should not start or end with .).
    Default: internal
    AllowedPattern: "[a-z][a-z0-9\\-.]*[a-z0-9]"
    ConstraintDescription: must contain only lowercase letters, numbers, dashes and dots
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the VPC in which the resources will be created.

Resources:
  InternalHostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Sub "${InternalDNSZone}.${FullyQualifiedExternalDNSZone}"
      VPCs:
      - VPCId: !Ref VPCId
        VPCRegion: !Ref "AWS::Region"

Outputs:
  FullyQualifiedInternalDNSZone:
    Description: The fully qualified internal DNS zone.
    Value: !Sub "${InternalDNSZone}.${FullyQualifiedExternalDNSZone}"
  InternalHostedZoneId:
    Description: The id of the internal DNS hosted zone.
    Value: !Ref InternalHostedZone
