---
  AWSTemplateFormatVersion: 2010-09-09

  Description: The VPC's NAT server.

  Parameters:
    AWSMusingsS3URL:
      Type: String
      Description: S3 path to aws-musings.
    DNSZone:
      Type: String
      Description: The DNS zone name of the VPC (should not end in 'vpc', used in naming the instance).
      AllowedPattern: "[a-z0-9\\-]*"
      ConstraintDescription: must contain only lowercase letters, numbers and dashes
    FullyQualifiedInternalParentDNSZone:
      Type: String
      Description: The internal parent DNS zone (should not start or end with .).
      AllowedPattern: "[a-z][a-z0-9\\-.]*[a-z0-9]"
      ConstraintDescription: must contain only lowercase letters, numbers, dashes and dots
    ImageId:
      Type: AWS::EC2::Image::Id
      Description: The AMI used to create the instance.
    KeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: SSH key name used to connect to the NAT server.
    SecurityGroupId:
      Type: AWS::EC2::SecurityGroup::Id
      Description: The id of the security group protecting the NAT server.
    SubnetId:
      Type: AWS::EC2::Subnet::Id
      Description: The id of the subnet where the server will be added.

  Resources:
    NATInstance:
      Type: AWS::EC2::Instance
      Metadata:
        "AWS::CloudFormation::Init":
          config:
            files:
              /etc/cfn/cfn-hup.conf:
                source: !Join [ /, [ !Ref AWSMusingsS3URL, common/cfn-hup.conf ] ]
                context:
                  STACK_ID: !Ref "AWS::StackId"
                  REGION: !Ref "AWS::Region"
                mode: 000400
                owner: root
                group: root
              /etc/cfn/hooks.d/cfn-auto-reloader.conf:
                source: !Join [ /, [ !Ref AWSMusingsS3URL, common/cfn-auto-reloader.conf ] ]
                context:
                  STACK_ID: !Ref "AWS::StackId"
                  REGION: !Ref "AWS::Region"
                  INSTANCE_NAME: NATInstance

              /etc/dhcp/dhclient.conf:
                source: !Join [ /, [ !Ref AWSMusingsS3URL, common/dhclient.conf ] ]
                context:
                  FQDN: !Join [ "", [ nat., !Ref DNSZone, ., !Ref FullyQualifiedInternalParentDNSZone ] ]
      Properties:
        DisableApiTermination: false
        SourceDestCheck: false
        ImageId: !Ref ImageId
        InstanceType: t2.nano
        KeyName: !Ref KeyName
        Monitoring: false
        Tags:
        - Key: Name
          Value: !Join [ -, [ !Ref DNSZone, nat ] ]
        NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet: [ !Ref SecurityGroupId ]
        UserData:
          Fn::Base64:
            !Join [ "", [
              "#!/bin/bash\n",

              "set -e -x\n",

              "export HOSTNAME=nat\n",
              "export STACK_NAME=\"", !Ref "AWS::StackName", "\"\n",
              "export RESOURCE=NATInstance\n",
              "export REGION=\"", !Ref "AWS::Region", "\"\n",
              "export AWS_MUSINGS_S3_URL=\"", !Ref AWSMusingsS3URL, "\"\n",

              "curl --output /tmp/bootstrap.sh --silent $AWS_MUSINGS_S3_URL/common/bootstrap.sh\n",
              "source /tmp/bootstrap.sh\n",
              "aws-bootstrap\n",

              "# All done so signal success\n",
              "aws-signal-success\n",
              "reboot\n"
            ] ]
      CreationPolicy:
        ResourceSignal:
          Timeout: PT10M

  Outputs:
    NATInstanceId:
      Description: This id of the NAT instance to be added to private route tables.
      Value: !Ref NATInstance
