AWSTemplateFormatVersion: 2010-09-09

Description: The private resources of a VPC.

Parameters:
  NATInstanceId:
    Type: String
    Description: The id of the NAT instance to be added to private route tables.
  EgressOnlyInternetGatewayId:
    Type: String
    Description: The id of the egress-only internet gateway for IPv6 traffic.
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the VPC in which the resources will be created.
  IPv6CIDRBlock:
    Type: String
    Description: The IPv6 CIDR block of the VPC. Optional, if not specified, no IPv6 capabilities will be configured.
    Type: String
    ConstraintDescription: must contain the first three quartets and half of the fourth quartet, optional
  VPNGatewayId:
    Type: String
    Description: |
      The VPN gateway to which route tables will be connected via route propagation. Optional, no propagation occurs
      if not specified.

Conditions:
  AddIPv6: !Not [ !Equals [ !Ref IPv6CIDRBlock, "" ] ]
  VPNGatewayIdDefined: !Not [ !Equals [ !Ref VPNGatewayId, "" ] ]

Resources:
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCId
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-private-rtb"
  IPv4PrivateDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PrivateRouteTable
      InstanceId: !Ref NATInstanceId
  IPv6PrivateDefaultRoute:
    Type: AWS::EC2::Route
    Condition: AddIPv6
    Properties:
      DestinationIpv6CidrBlock: ::/0
      RouteTableId: !Ref PrivateRouteTable
      EgressOnlyInternetGatewayId: !Ref EgressOnlyInternetGatewayId

  VPNGatewayRoutePropagation:
    Type: AWS::EC2::VPNGatewayRoutePropagation
    Condition: VPNGatewayIdDefined
    Properties:
      RouteTableIds: [ !Ref PrivateRouteTable ]
      VpnGatewayId: !Ref VPNGatewayId

Outputs:
  PrivateRouteTableId:
    Description: The id of the private route table.
    Value: !Ref PrivateRouteTable
