AWSTemplateFormatVersion: 2010-09-09

Description: A VPC.

Parameters:
  CIDRBlock:
    Type: String
    Description: The CIDR block of the VPC.
    Default: 10.0.0.0/16
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/\\d{1,2}"
    ConstraintDescription: must contain four dot-separated octets, a slash, and the network mask bit count

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDRBlock
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}"

Outputs:
  VPCId:
    Description: The id of the VPC in which the resources will be created.
    Value: !Ref VPC
