AWSTemplateFormatVersion: 2010-09-09

Description: VPN related resources.

Parameters:
  BGPASNumber:
    Type: Number
    Default: 65000
    Description: The Border Gateway Protocol Autonomous System Number.
  CustomerGatewayIPAddress:
    Type: String
    Description: The public IP address of the customer gateway.
  InternalAccessCIDRBlock:
    Type: String
    Description: The CIDR block that can access internal interfaces of public resources.
    Default: 10.0.0.0/8
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/\\d{1,2}"
    ConstraintDescription: must contain four dot-separated octets, a slash, and the network mask bit count
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the VPC in which the resources will be created.

Resources:
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties:
      Type: ipsec.1
      BgpAsn: !Ref BGPASNumber
      IpAddress: !Ref CustomerGatewayIPAddress
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-cgw"

  VPNGateway:
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-vgw"

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCId
      VpnGatewayId: !Ref VPNGateway

  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties:
      Type: ipsec.1
      StaticRoutesOnly: true
      CustomerGatewayId: !Ref CustomerGateway
      VpnGatewayId: !Ref VPNGateway
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-vpn-connection"

  VPNConnectionRoute:
    Type: AWS::EC2::VPNConnectionRoute
    Properties:
      DestinationCidrBlock: !Ref InternalAccessCIDRBlock
      VpnConnectionId: !Ref VPNConnection

Outputs:
  VPNGatewayId:
    Description: The VPN gateway to which route tables will be connected via route propagation.
    Value: !Ref VPNGateway
